theme: jekyll-theme-cayman
baseurl: /ai # https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
permalink: /:title:output_ext

collections:
  glossary:
    output: true
    permalink: /:path
